project_id: "751499"
base_url: "https://api.crowdin.com"
base_path: "."

preserve_hierarchy: true

commit_message: "[skip actions]"

files:
  - source: /src/*/i18n/template.pot
    translation: /%original_path%/%locale%.po
